[CCORE-282] Working around Dalli interaction with Elasticache memcach…
zendesk/kasket pull request #64
Opened 2021-07-17 02:33 UTC by snbloch

…ed nodes being rebooted

2021-07-17 02:33 UTC, snbloch commented
# Running:

/Users/steven.bloch/.rbenv/versions/2.6.8/lib/ruby/gems/2.6.0/gems/test_after_commit-0.4.2/lib/test_after_commit.rb:55: warning: instance variable @transaction not initialized
.../Users/steven.bloch/.rbenv/versions/2.6.8/lib/ruby/gems/2.6.0/gems/test_after_commit-0.4.2/lib/test_after_commit.rb:55: warning: instance variable @transaction not initialized
./Users/steven.bloch/.rbenv/versions/2.6.8/lib/ruby/gems/2.6.0/gems/test_after_commit-0.4.2/lib/test_after_commit.rb:55: warning: instance variable @transaction not initialized
./Users/steven.bloch/.rbenv/versions/2.6.8/lib/ruby/gems/2.6.0/gems/test_after_commit-0.4.2/lib/test_after_commit.rb:55: warning: instance variable @transaction not initialized
./Users/steven.bloch/.rbenv/versions/2.6.8/lib/ruby/gems/2.6.0/gems/test_after_commit-0.4.2/lib/test_after_commit.rb:55: warning: instance variable @transaction not initialized
.../Users/steven.bloch/.rbenv/versions/2.6.8/lib/ruby/gems/2.6.0/gems/test_after_commit-0.4.2/lib/test_after_commit.rb:55: warning: instance variable @transaction not initialized
../Users/steven.bloch/.rbenv/versions/2.6.8/lib/ruby/gems/2.6.0/gems/test_after_commit-0.4.2/lib/test_after_commit.rb:55: warning: instance variable @transaction not initialized
./Users/steven.bloch/.rbenv/versions/2.6.8/lib/ruby/gems/2.6.0/gems/test_after_commit-0.4.2/lib/test_after_commit.rb:55: warning: instance variable @transaction not initialized
./Users/steven.bloch/.rbenv/versions/2.6.8/lib/ruby/gems/2.6.0/gems/test_after_commit-0.4.2/lib/test_after_commit.rb:55: warning: instance variable @transaction not initialized
.../Users/steven.bloch/.rbenv/versions/2.6.8/lib/ruby/gems/2.6.0/gems/test_after_commit-0.4.2/lib/test_after_commit.rb:55: warning: instance variable @transaction not initialized
.../Users/steven.bloch/.rbenv/versions/2.6.8/lib/ruby/gems/2.6.0/gems/test_after_commit-0.4.2/lib/test_after_commit.rb:55: warning: instance variable @transaction not initialized
....................../Users/steven.bloch/.rbenv/versions/2.6.8/lib/ruby/gems/2.6.0/gems/test_after_commit-0.4.2/lib/test_after_commit.rb:55: warning: instance variable @transaction not initialized
...................................../Users/steven.bloch/.rbenv/versions/2.6.8/lib/ruby/gems/2.6.0/gems/test_after_commit-0.4.2/lib/test_after_commit.rb:55: warning: instance variable @transaction not initialized
./Users/steven.bloch/.rbenv/versions/2.6.8/lib/ruby/gems/2.6.0/gems/test_after_commit-0.4.2/lib/test_after_commit.rb:55: warning: instance variable @transaction not initialized
......./Users/steven.bloch/.rbenv/versions/2.6.8/lib/ruby/gems/2.6.0/gems/test_after_commit-0.4.2/lib/test_after_commit.rb:55: warning: instance variable @transaction not initialized
...

Finished in 0.623490s, 142.7449 runs/s, 336.8137 assertions/s.

89 runs, 210 assertions, 0 failures, 0 errors, 0 skips

2021-07-17 02:42 UTC, cryptomail approved these changes
Love it!
Hmm....any tests though?

2021-07-17 06:40 UTC, cryptomail requested changes
I will try to make so tests that exercise this

2021-07-17 15:46 UTC, grosser commented on test/find_some_test.rb
> +  describe "tests dalli_allow_true_class_response" do
```suggestion
  describe "with dalli_allow_true_class_response" do
```

2021-07-17 15:47 UTC, grosser commented on test/find_some_test.rb
> +    it "Does not raise error when dalli_allow_true_class_response set to false explicitly" do
```suggestion
    it "does not raise error when set to false" do
```

2021-07-17 15:48 UTC, grosser commented on lib/kasket.rb
> +    CONFIGURATION[:dalli_allow_true_class_response] = !!options[:dalli_allow_true_class_response] if options.key?(:dalli_allow_true_class_response)
isn't that the same ?
```suggestion
    CONFIGURATION[:dalli_allow_true_class_response] = !!options[:dalli_allow_true_class_response]
```

2021-07-17 15:51 UTC, grosser reviewed
dalli_allow_true_class_response sounds more like it would pass true up
maybe should be `dalli_fallback_on_error` or something like that

also sounds like true would never be a valid response since we cache AR objects, so can't it always do the fallback without needing extra config ?

2021-07-17 16:03 UTC, cryptomail commented
@grosser we were worried about existing behavior and safety.
If that is NOT a concern, will refactor, will rename, and make this default non switched behavior.

2021-07-17 16:18 UTC, grosser commented
better have this as opt-in first to find edge-cases and then promote to default
I'd still do the rename so it's more obvious what is happening under the hood
... if you check the code on what goes into/comes out of Kasket.cache.read and it is only AR objects then I'd say it's safe to be turned into default right away

2021-07-17 16:19 UTC, grosser commented
... the code would have always blown up with true, so I think this is safe to add without a guard

2021-07-17 16:24 UTC, grosser commented
https://api.rubyonrails.org/v6.1.4/classes/ActiveRecord/Querying.html#method-i-find_by_sql always returns an array as per the docs ... so we'd never store a true, so we can never pull out a true unless it's an error 🤷

2021-07-17 16:31 UTC, cryptomail commented
@grosser Got it, that's pretty reassuring and we kind of thought that, but wanted to ensure all AR versions had that return value.  I'm fairly certain if AR at one time had a differing return value (not just array type), it must have been ANCIENT history and a fair risk for consumers of this library if they're going back **that** far :)
So, I removed the guard, and made a poisoned cache test.

2021-07-19 17:13 UTC, mervync commented on lib/kasket/read_mixin.rb
> +              find_by_sql_without_kasket(*args)
(nit) maybe log a warning?

2021-07-19 17:13 UTC, mervync approved these changes
Ugh, it seems inappropriate to workaround this problem at this level. I'd expect

2021-07-19 18:36 UTC, cryptomail approved these changes
made tests

2021-07-19 21:42 UTC, merged